##### 1.Python Program to Add Two Numbers



In [ ]:

num1 = int(input("Enter First Number:"))

num2 = int(input("Enter Second Number:"))

sum = num1 + num2

print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))

The sum of 45 and 50 is 95


##### 2.Reverse a String

In [1]:
txt = "Hello World"
print(txt[::-1])


dlroW olleH


##### 3.Factorial of the number

In [ ]:
def factorial(x):
    if x == 0:
        return 1
    elif x==1:
        return 1
    else:
        return (x * factorial(x-1))
num = 4
result = factorial(num)
print("The factorial of", num, "is", result)

The factorial of 4 is 24


4.Check if a String is Palindrome(racecar=racecar)

In [ ]:
def isPalindrome(txt):
    return txt == txt[::-1]

txt = "racecar"
ans = isPalindrome(txt)
 
if ans:
    print("Given word --> {0} is Palindrome".format(txt))
else:
    print("Given word --> {0} is not a Palindrome".format(txt))

Given word --> racecar is Palindrome


5.Check the square of given number(Keyword:Exponential is written in python as  **0.5)

In [ ]:
num=int(input("Enter the number"))

num_sqrt=num ** 0.5

print('The squre root of %0.3f is %0.3f' %(num, num_sqrt))

The squre root of 16.000 is 4.000


7.Python programs to swap two variables(logic= x,y=y,x and temp=x, x=y , y=temp)

In [ ]:
x=16
y=15

temp=x
x=y
y=temp

print("The value of x after swapping:{}".format(x))
print("The vlaue of y after swapping: {}".format(y))

The value of x after swapping:15
The vlaue of y after swapping: 16


8.Python program to generate random number( using module "random", and function called randint= random.randint)

In [ ]:
import random

print(random.randint(0,9))

2


9.Check the number is Even or Odd [(num%2)==0]

In [ ]:
num=12

if (num % 2)==0:
    print("{0} is Even number".format(num))
else:
    print("{0} is Odd number".format(num))

print(num)

12 is Even number
12


10.Check if the Number is Positive , Negetive and Zero

In [ ]:
num=-250

if num > 0 :
    print("{0} is Positive Number".format(num))
elif num == 0:
    print("{0} is Zero".format(num))
else:
    print("{0} is Negative Number".format(num))

-250 is Negative Number


11.Find the largest amoung three numbers

In [ ]:
num1=2
num2=1
num3=133

if (num1>=num2) and (num1>=num3):
    print("Largest number", num1)
elif(num2>=num1) and (num2>=num3):
    print("Largest number", num2)
else:
    print("Largest number", num3)

Largest number 133


12.Program to check the prime number

In [ ]:
num=int(input("Enter the Prime Number"))

if num==1:
    print(num,"is not a prime number")
elif num > 1:
  for i in range(2, num):
    if(num % i)==0:
     print(num, "it is not a prime number")
     print(i, "times", num // i, "is", num)
     break
  else:
     print(num, "is a prime number")
else:
  print(num, "is not a prime number")




407 it is not a prime number
11 times 37 is 407


13.Print all the prime numbers within an interval

In [ ]:
lower=1
upper=100
count=0

print("Prime numbers between ", lower, "and", upper,"are")

for num in range(lower, upper +1 ):
    if num > 1:
        for i in range(2, num):
            if (num % i)==0:
                break
        else:
            print(num)
            count+= 1

print("Total number of Prime numbers between 1 and 100 is",str(count))

        







Prime numbers between  1 and 100 are
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
Total number of Prime numbers between 1 and 100 is 25


14. Find the Factorial of the Given Number

In [ ]:
num = 5

factorial = 1

if num < 0:
    print("Factorial does not exist for negative number")

elif num == 0:
    print("The factorial of 0 is 1")

else:

    for i in range(1, num + 1):
        factorial=factorial * i
    print("The factorial of ", num, "is", factorial)

The factorial of  5 is 120


15.Checking if a year is leap year or not

In [ ]:
year= 1600

if (year % 400 ==0) and (year % 100 ==0):
    print("{0} is leap year".format(year))
elif (year % 4 ==0) and (year % 100 !=0):
    print("{0} is leap year".format(year))

else:
    print("{0} is not a leap year".format(year))


1600 is leap year


16.Program to Display the Multiple table

In [ ]:
num = 4000

for i in range(1, 11):
    print(num,'x' , i,'=', num *i)

4000 x 1 = 4000
4000 x 2 = 8000
4000 x 3 = 12000
4000 x 4 = 16000
4000 x 5 = 20000
4000 x 6 = 24000
4000 x 7 = 28000
4000 x 8 = 32000
4000 x 9 = 36000
4000 x 10 = 40000


17.Program to Print Fibonacci Sequence

In [ ]:
nterms=int(input("How many times?"))

n1, n2 = 0, 1
count=0

if nterms <= 0:
    print("Please enter a positive integer")
elif nterms == 1:
    print("Fibonacci sequence upto",nterms, ":")
    print(n1)
else:
    print("Fibonnaci sequence")
    while count < nterms:
        print(n1)
        nth=n1 + n2
        n1=n2
        n2=nth
        count += 1


Fibonnaci sequence
0
1
1
2
3
5


18.Program to Check Armstrong Number

In [ ]:
num = 125

sum = 0

temp= num
while temp > 0:
    digit=temp % 10 
    sum += digit ** 3
    temp //= 10 

if num == sum :
    print(num, "is an armstrong number")

else:
    print(num, "is not an Armstrong number")

125 is not an Armstrong number


19.Program to Find Aramstrong number in interval

In [ ]:
lower=100
upper=2000

for num in range(lower, upper + 1):

    order=len(str(num))

   


    sum = 0

    temp = num

    while temp > 0:
        digit=temp % 10
        sum += digit ** order
        temp //= 10

    if num==sum:
        print(num)

153
370
371
407
1634


20.Find the Sum of Natural numbers

In [ ]:
num = 16

if num < 0:
    print("Entr a Positive number")

else:
    sum = 0

    while (num > 0):
        sum+=num 
        num-=1
    print("The sum is ", sum)


The sum is  136


21.Program to Display Powers of 2 Using Anonymus Function

In [ ]:
terms=5

result=list(map(lambda x:2 ** x, range(terms)))

print("The total terms are:", terms)
for i in range(terms):
    print("2 raised to power", i, "is", result[i])


The total terms are: 5
2 raised to power 0 is 1
2 raised to power 1 is 2
2 raised to power 2 is 4
2 raised to power 3 is 8
2 raised to power 4 is 16


22.Program to find Divisible by Another number

In [ ]:
my_list=[12, 65, 54, 39, 102, 339, 221]

result=list(filter(lambda x:(x % 13==0), my_list))

print("Numbers divisible by 13 are", result)

Numbers divisible by 13 are [65, 39, 221]


23.Covert Decimal to Binary, octal and Hexadecimal

In [ ]:
dec=2

print("The decimal value of:", dec ,"is")

print(bin(dec), "in binary")
print(oct(dec), "in octal")
print(hex(dec),"in hexadecimal")


The decimal value of: 2 is
0b10 in binary
0o2 in octal
0x2 in hexadecimal


24. Program to Find ASCII value of Character

In [ ]:
c='a'
print("The ASCII value of '" + c + " ' is", ord(c))

The ASCII value of 'a ' is 97


25.Program to Find HCF or GCD

In [ ]:
def compute_hcf(x, y):

    if x > y:
        smaller =y 
    else:
        smaller =x
    for i in range(1, smaller +1):
        if(x % i==0) and (y % i==0):
            hcf=i
    return hcf

num1=20
num2=60

print("The H. C. F is", compute_hcf(num1, num2))

The H. C. F is 20


26. Program to Find LCM

In [ ]:
def compute_lcm(x, y):

    if x > y:
        greater=x
    else:
        greater =y
    
    while(True):
        if((greater % x==0) and (greater % y==0)):
            lcm=greater
            break
        greater += 1

    return lcm

num1=120
num2=20

print(" The L.C.M ", compute_lcm(num1, num2))

 The L.C.M  120


27.Program to Find the factors of  Numbers

In [ ]:
def print_factors(x):
    print("The factors of", x, "are:")
    for i in range(1, x+1):
        if x % i ==0:
            print(i)

num=360
print_factors(num)

The factors of 360 are:
1
2
3
4
5
6
8
9
10
12
15
18
20
24
30
36
40
45
60
72
90
120
180
360


28. Program to Make Simple calculator 

In [1]:
def add(x, y):
    return x + y

def subtract(x,y):
    return x - y

def multiply(x ,y):
    return x * y
def divide(x, y):
    return x / y

print("Select operation:")
print("1. Add")
print("2. Subtract")
print("3.Multiply")
print("4. Divide")

while True:
    choice=input("Enter choice(1/2/3/4):")

    if choice in ('1', '2', '3', '4'):
        try:

            num1=float(input("Enter First number:"))
            num2=float(input("Enter second number:"))

        except ValueError:
            print("Invalid input. Please enter a number.")

        if choice=='1':
            print(num1, '+', num2, '=',add(num1, num2))

        elif choice == '2':
            print(num1,'-', num2,'=', subtract(num1, num2))
        elif choice == '3':
            print(num1,'*', num2,'=', multiply(num1, num2))
        elif choice == '4':
            print(num1,'/', num2,'=', divide(num1, num2))

        next_calculation=input("Let's do next calculation? (yes / No):")
        if next_calculation =="no":
            break
    else:
        print("Invalid Input")


Select operation:
1. Add
2. Subtract
3.Multiply
4. Divide


20.0 - 20.0 = 0.0
65.0 + 23.0 = 88.0
30.0 * 30.0 = 900.0
Invalid Input
Invalid Input
600.0 / 200.0 = 3.0


29.Program to Shuffle Deck of Cards

In [1]:
import itertools, random

deck =list(itertools.product(range(1,14),['spade','Heart','Diamod','Club']))

random.shuffle(deck)

print("You got:")
for i in range(5):
    print(deck[i][0],"of",deck[i][1])

You got:
6 of Club
5 of Heart
7 of Club
10 of Club
8 of Club


30.Program to Display the Calender

In [6]:
import calendar

yy=2023
mm=11

print(calendar.month(yy, mm))


   November 2023
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30



31.Program to fing sum of array

In [1]:
arr=[10,20,30]

ans=sum(arr)

print("Sum of an array is:", ans)

Sum of an array is: 60


Or 


In [3]:
def sum1(arr):

    sum=0

    for i in arr:

        sum=sum+i

    return(sum)

if __name__=="__main__":

    arr=[10,20,30]

    n=len(arr)

    ans=sum1(arr)

    print("Sum of the array is:", ans)

Sum of the array is: 60


32.Python program to find the largest element in an array

In [7]:
def largest (arr, n):
    max=arr[0]

    for i in range(1,n):
        if arr[i]>max:
            max=arr[i]
    return max

arr=[10,23,3333,4,5]
n=len(arr)
Ans=largest(arr, n)
print("Largest in given array", Ans)

Largest in given array 3333


33.Python program for array Rotation

In [2]:
def rotateArray(arr, n, d):
    temp=[]
    i=0
    while(i<d):
        temp.append(arr[i])
        i=i+1

    i=0
    while(d < n):
        arr[i] = arr[d]
        i=i+1
        d=d+1
    arr[:] = arr[: i] +temp
    return arr

arr=[1,2,3,4,5,6,7]
print("Array after left rotation is:", end=' ')
print(rotateArray(arr, len(arr),2))


Array after left rotation is: [3, 4, 5, 6, 7, 1, 2]


34.Python Program to split the array and add the first part to the end

In [4]:
def splitArr(arr, n,k):
    for i in range(0,k):
        x=arr[0]
        for j in range(0, n-1):
            arr[j]= arr[j+1]

        arr[n-1] = x


arr=[12,10,5,6,52,36]
n=len(arr)
position =2

splitArr(arr, n, position)

for i in range(0, n):
    print(arr[i], end=' ')

5 6 52 36 12 10 

35.Python program to find remainder of array multification divided by n

In [13]:
def findremainder(arr, lens, n):

    mul=1


    for i in range(lens):
        mul=(mul * (arr[i] % n)) % n

    return mul % n

arr=[100,10,5,25,35,14]
lens=len(arr)
n=11

print(findremainder(arr, lens,n))

TypeError: 'int' object is not callable

36.Python program to check if given array is monotonic

In [1]:
def isMonotonic(A):
    x,y=[],[]
    x.extend(A)
    y.extend(A)
    x.sort()
    y.sort(reverse=True)
    if(x==A or y==A):
        return True
    return False

A=[5,15,20,10]
print(isMonotonic(A))

False


37. Matrix --> Python program to add two Matrics


In [20]:
X=[[1,2,3],
   [4,5,6],
   [7,8,9]]
Y=[[9,8,7],
   [6,5,4],
   [3,2,1]]

result=[[X[i][j] + Y[i][j] for j in range (len(X[0]))] for i in range(len(X))]

for r in result:
    print(r)


TypeError: 'int' object is not callable

38.Python program for matrix Product

In [3]:
test_list=[[1,4,5],[7,3],[4],[46,7,3]]
x=[]
for i in test_list:
    x.extend(i)

res=1
for j in x:
    res *=j
print("The total element product in lists is:" +str(res))

The total element product in lists is:1622880


39.Adding and Subtracting matrics in Python

In [5]:
import numpy as np
 
 

A = np.array([[1, 2], [3, 4]])

B = np.array([[4, 5], [6, 7]])
 
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

print("Addition of two matrix")
print(np.add(A, B))
print("Subtraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


40. Using python Transpose a matrix in Single line 

In [6]:
import numpy
matrix = [[1, 2, 3], [4, 5, 6]]
print(matrix)
print("\n")
print(numpy.transpose(matrix))

[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


41.Python program to Matrix creation of n*n

In [7]:
N = 4
 

print("The dimension : " + str(N))
 

res = []
for i in range(N):
  row = []
  for j in range(N):
    row.append(1 + N * i + j)
  res.append(row)

print("The created matrix of N * N: " + str(res))

The dimension : 4
The created matrix of N * N: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


41.Get Kth column of Matrix

In [10]:

test_list = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]

print("The original list is : " + str(test_list))

K = 1
res = [sub[K] for sub in test_list]
print("The Kth column of matrix is : " + str(res))

The original list is : [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
The Kth column of matrix is : [5, 1, 12]


42. Python - Vertcial Concatenation in Matrix

In [11]:
from itertools import zip_longest
 

test_list = [["Gfg", "good"], ["is", "for"], ["Best"]]
 

print("The original list : " + str(test_list))
 

res = ["".join(ele) for ele in zip_longest(*test_list, fillvalue ="")]
 
print("List after column Concatenation : " + str(res))

The original list : [['Gfg', 'good'], ['is', 'for'], ['Best']]
List after column Concatenation : ['GfgisBest', 'goodfor']


43.Python program to check whether the string is Symmetrical or Palindrome

In [14]:
string = 'khokho'
half = int(len(string) / 2)
 
 
first_str = string[:half]
second_str = string[half:]
 
 

if first_str == second_str:
    print(string, 'string is symmetrical')
else:
    print(string, 'string is not symmetrical')
 

if first_str == second_str[::-1]:  # ''.join(reversed(second_str)) [slower]
    print(string, 'string is palindrome')
else:
    print(string, 'string is not palindrome')

khokho string is symmetrical
khokho string is not palindrome


44.Reverse words in a Given string in Python

In [15]:
string = "geeks quiz practice code"

s = string.split()[::-1]
l = []
for i in s:
    l.append(i)

print(" ".join(l))

code practice quiz geeks


45. Find the size of a Tuple in Python

In [16]:
Tuple1 = ("A", 1, "B", 2, "C", 3)
Tuple2 = ("Geek1", "Raju", "Geek2", "Nikhil", "Geek3", "Deepanshu")
Tuple3 = ((1, "Lion"), ( 2, "Tiger"), (3, "Fox"), (4, "Wolf"))
 

print("Size of Tuple1: " + str(Tuple1.__sizeof__()) + "bytes")
print("Size of Tuple2: " + str(Tuple2.__sizeof__()) + "bytes")
print("Size of Tuple3: " + str(Tuple3.__sizeof__()) + "bytes")

Size of Tuple1: 72bytes
Size of Tuple2: 72bytes
Size of Tuple3: 56bytes


46.Python Program for Binary Search(Recursice and Iterative)

In [24]:
def binary_search(arr, low, high, x):
 
 
    if high >= low:
 
        mid = (high + low) // 2
 
       
        if arr[mid] == x:
            return mid
 
       
        elif arr[mid] > x:
            return binary_search(arr, low, mid - 1, x)
 
        
        else:
            return binary_search(arr, mid + 1, high, x)
 
    else:
    
        return -1
 

arr = [ 2, 3, 4, 10, 40 ]
x = 2
 

result = binary_search(arr, 0, len(arr)-1, x)
 
if result != -1:
    print("Element is present at index", str(result))
else:
    print("Element is not present in array")

Element is present at index 0


47.Python program for linear search

In [34]:
def search(arr, x):
 
    for i in range(len(arr)):
 
        if arr[i] == x:
            return i
 
    return -1

arr=[12,13,4,5]
x=1

result = search(arr,x)
if result!=-1:
    print(result)
else:
    print("Element not in the list")


Element not in the list


48.Python Program for insertion sort

In [35]:
def insertionSort(arr):
    n = len(arr)  
      
    if n <= 1:
        return  
 
    for i in range(1, n):  
        key = arr[i] 
        j = i-1
        while j >= 0 and key < arr[j]:  
            arr[j+1] = arr[j]  
            j -= 1
        arr[j+1] = key 
  
arr = [12, 11, 13, 5, 6]
insertionSort(arr)
print(arr)

[5, 6, 11, 12, 13]


49. Python Program for Recursive insertion sort

In [36]:
def insertionSortRecursive(arr, n):

    if n <= 1:
        return
 
    
    insertionSortRecursive(arr, n - 1)
 
    
    last = arr[n - 1]
    j = n - 2
 

    while (j >= 0 and arr[j] > last):
        arr[j + 1] = arr[j]
        j = j - 1
    arr[j + 1] = last
 
 

if __name__ == '__main__':
    A = [-7, 11, 6, 0, -3, 5, 10, 2]
    n = len(A)
    insertionSortRecursive(A, n)
    print(A)
 


[-7, -3, 0, 2, 5, 6, 10, 11]


50.Print an Inverted star Pattern

In [4]:
def inverted_star_pattern_recursive(height):
    if height > 0:
        inverted_star_pattern_recursive(height - 1)
        print(height * "*")
 
height = 6
inverted_star_pattern_recursive(height)

*
**
***
****
*****
******


51.Program to print double sided stair - case pattern

In [2]:


def print_double_sided_staircase(height):
    for i in range(1, height + 1):
        for j in range(i):
            print("*", end="")
         
        print(" " * (2 * height - 2 * i), end="")
        
        for j in range(i):
            print("*", end="")
         
        print()  
height = int(input("Enter the height of the double-sided staircase: "))
print_double_sided_staircase(height)

*          *
**        **
***      ***
****    ****
*****  *****
************


52. Python Program to print the pattern 'G'

In [1]:
def Pattern(line): 
    pat="" 
    for i in range(0,line):     
        for j in range(0,line):      
            if ((j == 1 and i != 0 and i != line-1) or ((i == 0 or
                i == line-1) and j > 1 and j < line-2) or (i == ((line-1)/2) 
                and j > line-5 and j < line-1) or (j == line-2 and
                i != 0 and i != line-1 and i >=((line-1)/2))):   
                pat=pat+"*"   
            else:       
                pat=pat+" "   
        pat=pat+"\n"   
    return pat 
line = 7
print(Pattern(line)) 

  ***  
 *     
 *     
 * *** 
 *   * 
 *   * 
  ***  



53. Python program to swap first and element of the list

In [4]:
def swapList(newList):
    newList[0], newList[-1]= newList[-1], newList[0]

    return newList

newList=[12,3,5,6]
print(swapList(newList))



[6, 3, 5, 12]


54.Swap two elements in a  list using comma assginemsnt

In [7]:
def swapPositions(list, pos1, pos2):

    list[pos1], list[pos2]= list[pos2],list[pos1]
    return list

list=[12,3,5,6]
pos1, pos2= 1,3
print(swapPositions(list, pos1-1, pos2-1))

[5, 3, 12, 6]


55. Python program to find lenght of list

In [8]:
li=[10,20,2,4,5]
n=len(li)
print("The lenght of list is:", n)

The lenght of list is: 5


56.Program to check if element exist in list

In [11]:
lst=[ 1, 6, 3, 5, 3, 4 ]
i=5
if i in lst: 
    print("exist") 
else: 
    print("not exist")

exist


57. Clear a list in Python

In [12]:
My_list=[1,2,4,5]
print("Before", My_list)
My_list.clear()
print("After", My_list)

Before [1, 2, 4, 5]
After []


58.Reversing a List

In [21]:
def Reverse(lst):
    lst=lst[::-1]
    return lst

lst=[10,23,4,5,12,4]
print(Reverse(lst))

[4, 12, 5, 4, 23, 10]


59.Python Program to find sum of Elements in list

In [1]:

total = 0
 
list1 = [11, 5, 17, 18, 23]

for ele in range(0, len(list1)):
    total = total + list1[ele]

print("Sum of all elements in given list: ", total)

Sum of all elements in given list:  74


60.Python program to Multiplay all numbers in the list

In [5]:
def multiplylist(mylist):
    result=1

    for x in mylist:
        result=result * x
    return result

list1=[1,2,3]
list2=[3,2,6]
print(multiplylist(list1))
print(multiplylist(list2))

6
36


61.Python Program to find smallest number in a list

In [3]:
list1=[12,3,4,5]
list1.sort()
print("Smallest element is:", list1[0])

Smallest element is: 3


62.Python program to find second largest number in list

In [17]:
list1 = [10, 20, 20, 4,  45, 98, 99]
 
list2 = list(set(list1))
 

list2.sort()
 
print("Second largest element is:", list2[-2])

Second largest element is: 98


63. Python program to find N largest number in list

In [18]:



def Nmaxelements(list1, N):
	final_list = []

	for i in range(0, N):
		max1 = 0

		for j in range(len(list1)):
			if list1[j] > max1:
				max1 = list1[j]

		list1.remove(max1)
		final_list.append(max1)

	print(final_list)


list1 = [2, 6, 41, 85, 0, 3, 7, 6, 10]
N = 2
Nmaxelements(list1, N)


[85, 41]


64.Python program to print even numbers in a list

In [7]:
list1=[10, 12, 4]

for num in list1:
    if num % 2==0:
        print(num, end=" ")

10 12 4 

65. Pyhton program to print odd numbers in a list

In [9]:
list1=[10, 12, 4,5,56,89,1]

for num in list1:
    if num % 2!=0:
        print(num, end=" ")

5 89 1 

66.Python program to print all even numbers in a range

In [10]:
for even_numbers in range(4,15,2):

    print(even_numbers, end=" ")

4 6 8 10 12 14 

67.Python program to print positive numbers in a list

In [12]:
list1=[-10, 21 , 4 , -45 ,-66, 93, -11]

pos_num=list(filter(lambda x:(x>=0),list1))

print("Positive numbers in the list:", pos_num)

Positive numbers in the list: [21, 4, 93]


68.Python program to print negative numbers in a list

In [15]:
list1=[11,-21,0,45,66,-93]

for num in list1:
    if num < 0:
        print(num, end=" ")



-21 -93 

69.Python program to print all positive numbers in a range

In [19]:
start, end=-4, 19
for num in range(start , end +1 ):
    if num >= 0:
        print(num, end= " ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

70.Check if String Contains substring in Python

In [2]:
Mystring="Hardwork beats talent, Consistency makes hardwork"
if "Hardwork" in Mystring:
    print("Yes! it is present in string")
else:
    print("No! it is not presenet")



Yes! it is present in string


71.Find length of a string

In [7]:
str="Hello"
print( "Length of the given string is:",len(str))

Length of the given string is: 5


72.Python program to print even lenght words in string

In [13]:
def printWords(s):

    s=s.split(' ')

    for word in s:

        if len(word)%2==0:
            print(word)

s=" The Harder you work the better you get"
print(printWords(s))


Harder
work
better
None


73.Implementation of quick sort using python

In [4]:

def partition(array, low, high):

	
	pivot = array[high]

	
	i = low - 1

	
	for j in range(low, high):
		if array[j] <= pivot:

			i = i + 1

		
			(array[i], array[j]) = (array[j], array[i])


	(array[i + 1], array[high]) = (array[high], array[i + 1])

	
	return i + 1



def quicksort(array, low, high):
	if low < high:

		
		pi = partition(array, low, high)

		
		quicksort(array, low, pi - 1)

		quicksort(array, pi + 1, high)


if __name__ == '__main__':
	array = [10, 7, 8, 9, 1, 5]
	N = len(array)
	quicksort(array, 0, N - 1)
	print('Sorted array:')
	for x in array:
		print(x, end=" ")




Sorted array:
1 5 7 8 9 10 

74.Python program to read file word by word

In [5]:
file=open('Hello.txt', 'r')
for line in file:
    for word in line.split():
        print(word)

1
EarlyWakeup
2
Workout
3
Food
4
Coding
5
Repeat


75.Python program to read character by character form a file

In [6]:
file=open('Hello.txt', 'r')
while 1:

    char = file.read(1)
    if not char:
        break
    print(char)
file.close()

1
 
E
a
r
l
y
W
a
k
e
u
p
 
2
 
W
o
r
k
o
u
t
 
3
 
F
o
o
d
 
4
 
C
o
d
i
n
g
 
5
 
R
e
p
e
a
t


76.Count number of lines in a text file in python

In [7]:
file=open('Hello.txt','r')
lines=len(file.readlines())
print("Total Number of lines:", lines)

Total Number of lines: 1
